MAKEFILE_PATH:= $(call my-dir)
LAPACK_VERSION:=3.2.1
LAPACK_BASE_PATH:=$(MAKEFILE_PATH)/../CLAPACK-$(LAPACK_VERSION)
LAPACK_INCLUDES:=$(LAPACK_BASE_PATH)/INCLUDE
BLAS_SRC:=$(LAPACK_BASE_PATH)/BLAS/SRC

include $(CLEAR_VARS)

include $(MAKEFILE_PATH)/blas-config.mk

LOCAL_MODULE:= blas
LOCAL_PATH:= $(BLAS_SRC)
#LOCAL_CFLAGS:= -O3 -fPIC
LOCAL_C_INCLUDES:=$(BLAS_SRC) $(LAPACK_INCLUDES)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)
LOCAL_SRC_FILES:= $(ALLOBJ)  

#the inclusion of BLASWRAP caused unresolved symbols for TooN
#LOCAL_CFLAGS:= -DNO_BLAS_WRAP

ifeq ($(BLAS_BUILD_SHARED),true)
   include $(BUILD_SHARED_LIBRARY)
else
   include $(BUILD_STATIC_LIBRARY)
endif
